export const SEARCH_BREWERYS = "SEARCH_BREWERYS";
export const CLEAN_SEARCH_HISTORY = "CLEAN_SEARCH_HISTORY";
export const SAVE_TO_WISHLIST = "SAVE_TO_WISHLIST";
export const DISPLAY_FOOTPRINT = "DISPLAY_FOOTPRINT";
export const ADD_FOOTPRINT = "ADD_FOOTPRINT";
export const EDIT_FOOTPRINT = "EDIT_FOOTPRINT";
export const DELETE_FOOTPRINT = "DELETE_FOOTPRINT";
