export const SEARCH_RESTAURANTS = "SEARCH_RESTAURANTS";
export const SAVE_TO_WISHLIST = "SAVE_TO_WISHLIST";
export const ADD_FOOTPRINT = "ADD_FOOTPRINT";
export const EDIT_FOOTPRINT = "EDIT_FOOTPRINT";
export const DELETE_FOOTPRINT = "DELETE_FOOTPRINT";
